spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: slt
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8008
  servlet:
    context-path: /
  address:
mybatis:
  type-aliases-package: com.slt.producer
  mapper-locations: classpath:com/slt/producer/mapping/*.xml
logging:
  level:
    tk:
      mybatis: trace



